Use password auth type for keystone_auth for trusts
Without specifying 'password' for the auth type and using
trusts, we get the following error:

ERROR murano.common.engine [-] Exception 'NoneType' object has no attribute 'get_user_id' occurred during invocation of <system>: AttributeError: 'NoneType' object has no attribute 'get_user_id'
ERROR murano.common.engine Traceback (most recent call last):
ERROR murano.common.engine   File "/opt/murano/murano/common/engine.py", line 199, in execute
ERROR murano.common.engine     self._create_trust()
ERROR murano.common.engine   File "/opt/murano/murano/common/engine.py", line 318, in _create_trust
ERROR murano.common.engine     self._session.token, self._session.project_id)
ERROR murano.common.engine   File "/opt/murano/murano/common/auth_utils.py", line 98, in create_trust
ERROR murano.common.engine     trustee_user = admin_client.session.auth.get_user_id(admin_client.session)
ERROR murano.common.engine AttributeError: 'NoneType' object has no attribute 'get_user_id'

This is easily worked around by setting the auth_type to
be 'password', so this should become the default.

We also ensure that murano_auth/www_authenticate_uri exists,
to prevent the following stack trace:

ERROR murano.common.engine [-] Exception 'NoneType' object has no attribute 'replace' occurred during invocation of <system>: AttributeError: 'NoneType' object has no attribute 'replace'
ERROR murano.common.engine Traceback (most recent call last):
ERROR murano.common.engine   File "/opt/murano/murano/common/engine.py", line 199, in execute
ERROR murano.common.engine     self._create_trust()
ERROR murano.common.engine   File "/opt/murano/murano/common/engine.py", line 318, in _create_trust
ERROR murano.common.engine     self._session.token, self._session.project_id)
ERROR murano.common.engine   File "/opt/murano/murano/common/auth_utils.py", line 97, in create_trust
ERROR murano.common.engine     token=trustee_token, project_id=trustee_project_id)
ERROR murano.common.engine   File "/opt/murano/murano/common/auth_utils.py", line 91, in create_keystone_client
ERROR murano.common.engine     token=token, project_id=project_id, conf=conf))
ERROR murano.common.engine   File "/opt/murano/murano/common/auth_utils.py", line 76, in get_token_client_session
ERROR murano.common.engine     auth_url = www_authenticate_uri.replace('v2.0', 'v3')
ERROR murano.common.engine AttributeError: 'NoneType' object has no attribute 'replace'

Once keystone::resource::auth_token starts to use www_authenticate_uri,
this shouldn't be an issue any more.

Change-Id: I2509a88b6dac35d6d3dbebccc9058823e2a85991